### ISSUE TITLE
[FEAT] QA 제일 중요 우선순위 기능

### ISSUE THREAD

**Issue by Hanna922** [ALL-CHIVE/All-Chive-Mobile#148]
## Description
09.04 업데이트 제일 중요 QA

## TODO

- [x] BoxButton 하단 여백 수정
- [x] 아카이빙 페이지 일러스트 수정
- [x] 홈 카테고리 디자인 수정
